version: 2.1
jobs:
  build:
    docker:
        - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$TAG .
          docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$TAG $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          
workflows:
  build_push_docker:
    jobs:
      - build
  monthly_update:
    triggers:
      - schedule: 
          cron: "0 0 3 * *"
          filters:
            branches:
              only:
                - master
    jobs: 
      - build